
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dndwellers_development

test:
  <<: *default
  database: dndwellers_test

production:
  <<: *default
  database: dndwellers_production
  username: dndwellers
  password: <%= ENV['dndwellers_DATABASE_PASSWORD'] %>
